
function [fcMatrix_HFD_DCGF, pMatrix_HFD_DCGF,...
          fcMatrix_CTR_DCGF, pMatrix_CTR_DCGF,...
          fcMatrix_DC_HFDCTR, pMatrix_DC_HFDCTR,...
          fcMatrix_GF_HFDCTR, pMatrix_GF_HFDCTR] = workflow_DifferentialAnalysisHFD(totDataMat,...
                                                                           totDataDiet,...
                                                                           totDataCondition)
% perform differential analysis of metabolite data 
% between GF and DC (defined community) mice
% between HFD (high fat) and CTR diets

%%%%%%%%%HFD, DC vs GF %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fcMatrix_HFD_DCGF = (nanmean(totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'DC')),2)./...
                     nanmean(totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'GF')),2));
                    
[~, pMatrix_HFD_DCGF] = ttest2(totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'DC')),...
                                  totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'GF')),...
                                  'Dim', 2, 'VarType', 'equal');
%%%%%%%%%CTR, DC vs GF %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fcMatrix_CTR_DCGF = (nanmean(totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'DC')),2)./...
                     nanmean(totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'GF')),2));
[~, pMatrix_CTR_DCGF] = ttest2(totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'DC')),...
                                  totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'GF')),...
                                  'Dim', 2, 'VarType', 'equal');
%%%%%%%%%DC, HFD vs CTR %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fcMatrix_DC_HFDCTR = (nanmean(totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'DC')),2)./...
                     nanmean(totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'DC')),2));
[~, pMatrix_DC_HFDCTR] = ttest2(totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'DC')),...
                                  totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'DC')),...
                                  'Dim', 2, 'VarType', 'equal');
%%%%%%%%%GF, HFD vs CTR %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fcMatrix_GF_HFDCTR = (nanmean(totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'GF')),2)./...
                     nanmean(totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'GF')),2));
[~, pMatrix_GF_HFDCTR] = ttest2(totDataMat(:, ismember(totDataDiet, 'HFD') &...
                                           ismember(totDataCondition, 'GF')),...
                                  totDataMat(:, ismember(totDataDiet, 'CTR') &...
                                           ismember(totDataCondition, 'GF')),...
                                  'Dim', 2, 'VarType', 'equal');

